package models

import (
	"log"

	"gorm.io/gorm"
)

func SeedInitialData(db *gorm.DB) {
	// 1. Seed Test Users (Pre-verified test accounts for every platform role)
	// Password for all test users: Carplug2026!
	const testPasswordHash = "$2b$10$PoSj3o7yeFznCHC4cE/BgOEnaAJgMbrvove.sjnjXkwvmBjnf9lOy"

	testUsers := []User{
		{
			ID:           "usr-admin",
			Name:         "Super Admin",
			Email:        "admin@mycars.ng",
			Phone:        "+2348000000001",
			PasswordHash: testPasswordHash,
			Role:         string(RoleAdmin),
			IsVerified:   true,
		},
		{
			ID:           "usr-dealer-reed",
			Name:         "Reed Motors Lagos",
			Email:        "dealer.reed@mycars.ng",
			Phone:        "+2348035004401",
			PasswordHash: testPasswordHash,
			Role:         string(RoleDealer),
			IsVerified:   true,
		},
		{
			ID:           "usr-dealer-crown",
			Name:         "Crown Continental Autos",
			Email:        "dealer.crown@mycars.ng",
			Phone:        "+2348127708820",
			PasswordHash: testPasswordHash,
			Role:         string(RoleDealer),
			IsVerified:   true,
		},
		{
			ID:           "usr-dealer-apex",
			Name:         "Apex Exotic Motors",
			Email:        "dealer.apex@mycars.ng",
			Phone:        "+2348023337799",
			PasswordHash: testPasswordHash,
			Role:         string(RoleDealer),
			IsVerified:   true,
		},
		{
			ID:           "usr-seller-babatunde",
			Name:         "Babatunde Olumide",
			Email:        "seller.babatunde@mycars.ng",
			Phone:        "+2349012223344",
			PasswordHash: testPasswordHash,
			Role:         string(RoleSeller),
			IsVerified:   true,
		},
		{
			ID:           "usr-tech-musa",
			Name:         "Musa Danladi, ASE-Cert",
			Email:        "tech.musa@mycars.ng",
			Phone:        "+2348051118899",
			PasswordHash: testPasswordHash,
			Role:         string(RoleTechnician),
			IsVerified:   true,
		},
		{
			ID:           "usr-buyer-chidi",
			Name:         "Dr. Chidi Nwosu",
			Email:        "buyer.chidi@mycars.ng",
			Phone:        "+2348032910021",
			PasswordHash: testPasswordHash,
			Role:         string(RoleBuyer),
			IsVerified:   true,
		},
	}

	log.Println("[Seed] Upserting platform test users...")
	for _, u := range testUsers {
		var existing User
		if err := db.Where("email = ?", u.Email).First(&existing).Error; err != nil {
			if err == gorm.ErrRecordNotFound {
				db.Create(&u)
			}
		} else {
			db.Model(&existing).Updates(map[string]interface{}{
				"role":          u.Role,
				"password_hash": u.PasswordHash,
				"is_verified":   true,
				"phone":         u.Phone,
				"name":          u.Name,
			})
		}
	}

	// 2. Seed Dealer Shops
	dealers := []DealerShop{
		{
			ID:                  "dealer-reed-motors",
			UserID:              "usr-dealer-reed",
			Slug:                "reed-motors-lagos",
			Name:                "Reed Motors Lagos",
			Tagline:             "Certified Tokunbo & Luxury Vehicles with Independent Trust Scoring",
			Logo:                "",
			Banner:              "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679253/carplug/brand/hero-car.webp",
			Location:            "Lekki Phase 1, Lagos",
			Address:             "Plot 14 Admiralty Way, Lekki Phase 1, Lagos State",
			Rating:              4.9,
			ReviewCount:         74,
			VerifiedCAC:         true,
			Plan:                "Premium Shop",
			ActiveListingsCount: 5,
			Phone:               "+234 803 500 4401",
			Whatsapp:            "+2348035004401",
			Email:               "dealer.reed@mycars.ng",
			OperatingHours:      "Mon - Sat: 8:00 AM - 6:30 PM",
			JoinedDate:          "January 2026",
		},
		{
			ID:                  "dealer-crown-autos",
			UserID:              "usr-dealer-crown",
			Slug:                "crown-continental-autos",
			Name:                "Crown Continental Autos",
			Tagline:             "Direct US & Canadian Import Specialist Since 2018",
			Logo:                "",
			Banner:              "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679253/carplug/brand/hero-car.webp",
			Location:            "Ikeja GRA, Lagos",
			Address:             "12 Isaac John St, Ikeja GRA, Lagos State",
			Rating:              4.7,
			ReviewCount:         42,
			VerifiedCAC:         true,
			Plan:                "Pro Shop",
			ActiveListingsCount: 5,
			Phone:               "+234 812 770 8820",
			Whatsapp:            "+2348127708820",
			Email:               "dealer.crown@mycars.ng",
			OperatingHours:      "Mon - Sat: 8:30 AM - 6:00 PM",
			JoinedDate:          "March 2026",
		},
		{
			ID:                  "dealer-apex-motors",
			UserID:              "usr-dealer-apex",
			Slug:                "apex-exotic-motors",
			Name:                "Apex Exotic Motors",
			Tagline:             "Premier Showroom for Brand New Luxury, Supercars & Next-Gen EVs",
			Logo:                "",
			Banner:              "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679253/carplug/brand/hero-car.webp",
			Location:            "Victoria Island, Lagos",
			Address:             "Ahmadu Bello Way, Victoria Island, Lagos State",
			Rating:              5.0,
			ReviewCount:         31,
			VerifiedCAC:         true,
			Plan:                "Premium Shop",
			ActiveListingsCount: 4,
			Phone:               "+234 802 333 7799",
			Whatsapp:            "+2348023337799",
			Email:               "dealer.apex@mycars.ng",
			OperatingHours:      "Mon - Sat: 9:00 AM - 7:00 PM",
			JoinedDate:          "May 2026",
		},
	}
	log.Println("[Seed] Upserting DealerShops...")
	for _, d := range dealers {
		db.Save(&d)
	}

	// 3. Seed Technicians
	techs := []Technician{
		{
			ID:              "tech-musa",
			Name:            "Musa Danladi, ASE-Cert",
			Badge:           "Preferred Master",
			Avatar:          "",
			Rating:          4.95,
			CompletedJobs:   218,
			ServiceAreas:    `["Lekki Phase 1", "Ikoyi", "Victoria Island", "Ajah"]`,
			WorkshopAddress: "Block 8 Autocare Center, Maroko, Lekki",
			Specialties:     `["Toyota / Lexus Hybrid Systems", "Mercedes-Benz Star Diagnostics", "Chassis Structural Laser Scan"]`,
			DistanceKm:      3.2,
			Availability:    "Available Today",
			HourlyRate:      15000,
		},
		{
			ID:              "tech-kunle",
			Name:            "Engr. Kunle Adeleke",
			Badge:           "Platform Certified",
			Avatar:          "",
			Rating:          4.82,
			CompletedJobs:   146,
			ServiceAreas:    `["Ikeja", "Maryland", "Magodo", "Ogba"]`,
			WorkshopAddress: "14 Mobolaji Bank Anthony Way, Ikeja",
			Specialties:     `["German Powertrains (BMW/Audi)", "Transmission Valve Body Overhauls", "OBD-II Live Telemetry"]`,
			DistanceKm:      6.8,
			Availability:    "Available Today",
			HourlyRate:      12000,
		},
		{
			ID:              "tech-emmanuel",
			Name:            "Emmanuel Chukwu",
			Badge:           "Standard Specialist",
			Avatar:          "",
			Rating:          4.70,
			CompletedJobs:   89,
			ServiceAreas:    `["Surulere", "Yaba", "Gbagada"]`,
			WorkshopAddress: "Plot 3 Western Avenue, Surulere",
			Specialties:     `["Japanese Everyday Daily Drivers", "Suspension & Braking Systems", "Pre-Purchase Document Audit"]`,
			DistanceKm:      11.4,
			Availability:    "Next Available Tomorrow",
			HourlyRate:      10000,
		},
	}
	log.Println("[Seed] Upserting Technicians...")
	for _, t := range techs {
		db.Save(&t)
	}

	// 4. Seed Comprehensive Vehicles Catalog (Covering all Categories, Body Types, Brands, Conditions & Dealers)
	vehicles := []Vehicle{
		// --- SUV Category ---
		{
			ID:                 "v-lexus-rx350-2021",
			Title:              "2021 Lexus RX 350 F-Sport AWD",
			Year:               2021,
			Make:               "Lexus",
			Model:              "RX",
			Trim:               "F-Sport AWD",
			BodyType:           "SUV",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            28400,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.5L V6",
			VIN:                "2T2HZMCA4MC189402",
			Price:              34500000,
			MarketPriceMin:     32000000,
			MarketPriceMax:     36000000,
			PriceRating:        "fair",
			PriceVerdict:       "Fair market valuation based on verified recent Lekki/Ikeja sales of Tokunbo F-Sport trims.",
			TrustTier:          5,
			TrustTierLabel:     "Premium Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679186/carplug/cars/car15.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679188/carplug/cars/car17.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679189/carplug/cars/car18.jpg"]`,
			PublicLocation:     "Lekki Phase 1, Lagos",
			ExactLocation:      "Plot 14 Admiralty Way, Lekki",
			SellerID:           "dealer-reed-motors",
			SellerType:         "dealer",
			SellerName:         "Reed Motors Lagos",
			SellerPhone:        "+234 803 500 4401",
			SellerRating:       4.9,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			TintPermit:         true,
			PoliceExtracted:    true,
			HealthScore:        92,
			LatestInspectionID: "insp-001",
			Featured:           true,
		},
		{
			ID:                 "v-mercedes-gle450-2022",
			Title:              "2022 Mercedes-Benz GLE 450 4MATIC AMG-Line",
			Year:               2022,
			Make:               "Mercedes-Benz",
			Model:              "GLE",
			Trim:               "450 4MATIC AMG",
			BodyType:           "SUV",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            19800,
			Transmission:       "Automatic",
			FuelType:           "Hybrid",
			EngineSize:         "3.0L Turbo Inline-6 EQ Boost",
			VIN:                "4JGDA5JB6NB310492",
			Price:              68000000,
			MarketPriceMin:     65000000,
			MarketPriceMax:     71000000,
			PriceRating:        "fair",
			PriceVerdict:       "Price aligns with low mileage and documented customs duties cleared at Tin Can port.",
			TrustTier:          4,
			TrustTierLabel:     "Technician Inspected",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679188/carplug/cars/car17.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679186/carplug/cars/car15.jpg"]`,
			PublicLocation:     "Victoria Island, Lagos",
			ExactLocation:      "Ahmadu Bello Way, VI",
			SellerID:           "dealer-reed-motors",
			SellerType:         "dealer",
			SellerName:         "Reed Motors Lagos",
			SellerPhone:        "+234 803 500 4401",
			SellerRating:       4.9,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    false,
			Roadworthiness:     true,
			HealthScore:        88,
			LatestInspectionID: "insp-003",
			Featured:           true,
		},
		{
			ID:                 "v-toyota-lc300-2024",
			Title:              "2024 Toyota Land Cruiser 300 VXR 3.5L Twin Turbo",
			Year:               2024,
			Make:               "Toyota",
			Model:              "Land Cruiser",
			Trim:               "300 VXR",
			BodyType:           "SUV",
			Condition:          "Brand New",
			Mileage:            45,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.5L Twin-Turbo V6",
			VIN:                "JTEPC01J20K009182",
			Price:              155000000,
			MarketPriceMin:     150000000,
			MarketPriceMax:     162000000,
			PriceRating:        "fair",
			PriceVerdict:       "Competitive pricing for brand new flagship 300-series with manufacturer warranty.",
			TrustTier:          5,
			TrustTierLabel:     "Premium Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679180/carplug/cars/car5.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679186/carplug/cars/car15.jpg"]`,
			PublicLocation:     "Victoria Island, Lagos",
			ExactLocation:      "Ahmadu Bello Way, VI",
			SellerID:           "dealer-apex-motors",
			SellerType:         "dealer",
			SellerName:         "Apex Exotic Motors",
			SellerPhone:        "+234 802 333 7799",
			SellerRating:       5.0,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        100,
			Featured:           true,
		},
		{
			ID:                 "v-ford-explorer-2018",
			Title:              "2018 Ford Explorer Limited 4WD (7-Seater)",
			Year:               2018,
			Make:               "Ford",
			Model:              "Explorer",
			Trim:               "Limited 4WD",
			BodyType:           "SUV",
			Condition:          "Nigerian Used",
			Mileage:            74200,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.5L V6",
			VIN:                "1FM5K8F84JGA81920",
			Price:              18500000,
			MarketPriceMin:     17500000,
			MarketPriceMax:     20000000,
			PriceRating:        "deal",
			PriceVerdict:       "Priced below market average for single-owner Nigerian used 7-seater SUV.",
			TrustTier:          3,
			TrustTierLabel:     "Platform Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679182/carplug/cars/car10.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679183/carplug/cars/car11.jpg"]`,
			PublicLocation:     "Surulere, Lagos",
			SellerID:           "seller-babatunde",
			SellerType:         "private",
			SellerName:         "Babatunde Olumide",
			SellerPhone:        "+234 901 222 3344",
			SellerRating:       4.6,
			CustomsStatus:      "Local Registration",
			CustomsDoc:         false,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        79,
			Featured:           false,
		},

		// --- Sedan Category ---
		{
			ID:                 "v-toyota-camry-2020",
			Title:              "2020 Toyota Camry XSE V6 (Panoramic Roof)",
			Year:               2020,
			Make:               "Toyota",
			Model:              "Camry",
			Trim:               "XSE V6",
			BodyType:           "Sedan",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            32400,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.5L V6",
			VIN:                "4T1B11HK5LU821903",
			Price:              24800000,
			MarketPriceMin:     25500000,
			MarketPriceMax:     28000000,
			PriceRating:        "deal",
			PriceVerdict:       "Below comparable market range — ₦1.8m lower than average Tokunbo XSE listings.",
			TrustTier:          4,
			TrustTierLabel:     "Technician Inspected",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679184/carplug/cars/car13.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679187/carplug/cars/car16.jpg"]`,
			PublicLocation:     "Ikeja GRA, Lagos",
			ExactLocation:      "Isaac John Street, Ikeja",
			SellerID:           "dealer-crown-autos",
			SellerType:         "dealer",
			SellerName:         "Crown Continental Autos",
			SellerPhone:        "+234 812 770 8820",
			SellerRating:       4.7,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        84,
			LatestInspectionID: "insp-002",
			Featured:           true,
		},
		{
			ID:                 "v-toyota-corolla-2018",
			Title:              "2018 Toyota Corolla LE (First Body)",
			Year:               2018,
			Make:               "Toyota",
			Model:              "Corolla",
			Trim:               "LE",
			BodyType:           "Sedan",
			Condition:          "Nigerian Used",
			Mileage:            82000,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "1.8L 4-Cylinder",
			VIN:                "2T1BURHE7JC982103",
			Price:              13500000,
			MarketPriceMin:     12000000,
			MarketPriceMax:     14000000,
			PriceRating:        "fair",
			PriceVerdict:       "Standard Nigerian-used pricing for single-owner vehicle with factory original paint.",
			TrustTier:          3,
			TrustTierLabel:     "Platform Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679177/carplug/cars/car1.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679178/carplug/cars/car2.jpg"]`,
			PublicLocation:     "Surulere, Lagos",
			SellerID:           "seller-babatunde",
			SellerType:         "private",
			SellerName:         "Babatunde Olumide",
			SellerPhone:        "+234 901 222 3344",
			SellerRating:       4.6,
			CustomsStatus:      "Local Registration",
			CustomsDoc:         false,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        78,
			Featured:           false,
		},
		{
			ID:                 "v-mercedes-c300-2024",
			Title:              "2024 Mercedes-Benz C300 AMG Line 4MATIC",
			Year:               2024,
			Make:               "Mercedes-Benz",
			Model:              "C-Class",
			Trim:               "C300 AMG Line",
			BodyType:           "Sedan",
			Condition:          "Brand New",
			Mileage:            20,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "2.0L Turbo Inline-4 EQ Boost",
			VIN:                "W1KAF8FB7RR102948",
			Price:              76000000,
			MarketPriceMin:     74000000,
			MarketPriceMax:     80000000,
			PriceRating:        "fair",
			PriceVerdict:       "Official showroom specification with digital light package and Burmester surround.",
			TrustTier:          5,
			TrustTierLabel:     "Premium Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679181/carplug/cars/car7.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679184/carplug/cars/car12.jpg"]`,
			PublicLocation:     "Victoria Island, Lagos",
			ExactLocation:      "Ahmadu Bello Way, VI",
			SellerID:           "dealer-apex-motors",
			SellerType:         "dealer",
			SellerName:         "Apex Exotic Motors",
			SellerPhone:        "+234 802 333 7799",
			SellerRating:       5.0,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        99,
			Featured:           true,
		},
		{
			ID:                 "v-honda-accord-2020",
			Title:              "2020 Honda Accord Touring 2.0T",
			Year:               2020,
			Make:               "Honda",
			Model:              "Accord",
			Trim:               "Touring 2.0T",
			BodyType:           "Sedan",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            41000,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "2.0L Turbo 4-Cylinder",
			VIN:                "1HGCV2F97LA048192",
			Price:              21500000,
			MarketPriceMin:     21000000,
			MarketPriceMax:     23500000,
			PriceRating:        "deal",
			PriceVerdict:       "High-spec Touring trim with heads-up display and ventilated seats at great value.",
			TrustTier:          4,
			TrustTierLabel:     "Technician Inspected",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679185/carplug/cars/car14.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679186/carplug/cars/car15.jpg"]`,
			PublicLocation:     "Ikeja GRA, Lagos",
			SellerID:           "dealer-crown-autos",
			SellerType:         "dealer",
			SellerName:         "Crown Continental Autos",
			SellerPhone:        "+234 812 770 8820",
			SellerRating:       4.7,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        86,
			Featured:           false,
		},

		// --- Coupe Category ---
		{
			ID:                 "v-bmw-m4-2021",
			Title:              "2021 BMW M4 Competition Coupe (Carbon Pack)",
			Year:               2021,
			Make:               "BMW",
			Model:              "M3 / M4",
			Trim:               "Competition",
			BodyType:           "Coupe",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            18500,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.0L Twin-Turbo Inline-6",
			VIN:                "WBS43AY02MCF91024",
			Price:              58000000,
			MarketPriceMin:     56000000,
			MarketPriceMax:     62000000,
			PriceRating:        "fair",
			PriceVerdict:       "Verified clean CarFax with carbon ceramic brake option and M Driver package.",
			TrustTier:          5,
			TrustTierLabel:     "Premium Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679179/carplug/cars/car4.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679177/carplug/cars/car1.jpg"]`,
			PublicLocation:     "Lekki Phase 1, Lagos",
			ExactLocation:      "Plot 14 Admiralty Way, Lekki",
			SellerID:           "dealer-reed-motors",
			SellerType:         "dealer",
			SellerName:         "Reed Motors Lagos",
			SellerPhone:        "+234 803 500 4401",
			SellerRating:       4.9,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        94,
			Featured:           true,
		},
		{
			ID:                 "v-audi-rs5-2020",
			Title:              "2020 Audi RS5 Coupe Quattro Sport",
			Year:               2020,
			Make:               "Audi",
			Model:              "RS5",
			Trim:               "Coupe Quattro",
			BodyType:           "Coupe",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            24000,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "2.9L Twin-Turbo V6",
			VIN:                "WAUB8AF53LA901842",
			Price:              48000000,
			MarketPriceMin:     47000000,
			MarketPriceMax:     52000000,
			PriceRating:        "deal",
			PriceVerdict:       "Excellent enthusiast performance value with Dynamic Ride Control suspension.",
			TrustTier:          4,
			TrustTierLabel:     "Technician Inspected",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679190/carplug/cars/car19.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679191/carplug/cars/car20.jpg"]`,
			PublicLocation:     "Ikeja GRA, Lagos",
			SellerID:           "dealer-crown-autos",
			SellerType:         "dealer",
			SellerName:         "Crown Continental Autos",
			SellerPhone:        "+234 812 770 8820",
			SellerRating:       4.7,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        89,
			Featured:           true,
		},

		// --- Jeep & Truck Category ---
		{
			ID:                 "v-jeep-wrangler-2020",
			Title:              "2020 Jeep Wrangler Unlimited Rubicon 4x4",
			Year:               2020,
			Make:               "Jeep",
			Model:              "Wrangler",
			Trim:               "Rubicon 4x4",
			BodyType:           "Jeep",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            33000,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.6L Pentastar V6",
			VIN:                "1C4HJXFG2LW190284",
			Price:              38000000,
			MarketPriceMin:     36000000,
			MarketPriceMax:     40000000,
			PriceRating:        "fair",
			PriceVerdict:       "Factory Fox shocks, rock rails, and electronic sway bar disconnect tested good.",
			TrustTier:          4,
			TrustTierLabel:     "Technician Inspected",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679178/carplug/cars/car3.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679180/carplug/cars/car5.jpg"]`,
			PublicLocation:     "Maitama, Abuja",
			SellerID:           "seller-babatunde",
			SellerType:         "private",
			SellerName:         "Babatunde Olumide",
			SellerPhone:        "+234 901 222 3344",
			SellerRating:       4.6,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        88,
			Featured:           true,
		},
		{
			ID:                 "v-ford-f150-2021",
			Title:              "2021 Ford F-150 Lariat SuperCrew 4x4 FX4",
			Year:               2021,
			Make:               "Ford",
			Model:              "F-150",
			Trim:               "Lariat FX4",
			BodyType:           "Jeep",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            29000,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.5L EcoBoost V6",
			VIN:                "1FTFW1ED6MFA82019",
			Price:              42000000,
			MarketPriceMin:     40000000,
			MarketPriceMax:     45000000,
			PriceRating:        "deal",
			PriceVerdict:       "Equipped with Pro Power Onboard and 12-inch SYNC 4 display.",
			TrustTier:          4,
			TrustTierLabel:     "Technician Inspected",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679182/carplug/cars/car10.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679183/carplug/cars/car11.jpg"]`,
			PublicLocation:     "Ikeja GRA, Lagos",
			SellerID:           "dealer-crown-autos",
			SellerType:         "dealer",
			SellerName:         "Crown Continental Autos",
			SellerPhone:        "+234 812 770 8820",
			SellerRating:       4.7,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        87,
			Featured:           false,
		},

		// --- Hatchback Category ---
		{
			ID:                 "v-vw-golf-2019",
			Title:              "2019 Volkswagen Golf GTI 2.0T DSG",
			Year:               2019,
			Make:               "Volkswagen",
			Model:              "Golf",
			Trim:               "GTI Performance",
			BodyType:           "Hatchback",
			Condition:          "Nigerian Used",
			Mileage:            64000,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "2.0L Turbo 4-Cylinder",
			VIN:                "3VW547AU5KM091824",
			Price:              16500000,
			MarketPriceMin:     15500000,
			MarketPriceMax:     18000000,
			PriceRating:        "fair",
			PriceVerdict:       "Well-maintained hot hatch with clean service logs from authorized VW garage.",
			TrustTier:          3,
			TrustTierLabel:     "Platform Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679178/carplug/cars/car2.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679177/carplug/cars/car1.jpg"]`,
			PublicLocation:     "Yaba, Lagos",
			SellerID:           "seller-babatunde",
			SellerType:         "private",
			SellerName:         "Babatunde Olumide",
			SellerPhone:        "+234 901 222 3344",
			SellerRating:       4.6,
			CustomsStatus:      "Local Registration",
			CustomsDoc:         false,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        82,
			Featured:           false,
		},

		// --- Convertible Category ---
		{
			ID:                 "v-bmw-z4-2023",
			Title:              "2023 BMW Z4 M40i Roadster Convertible",
			Year:               2023,
			Make:               "BMW",
			Model:              "Z4",
			Trim:               "M40i Roadster",
			BodyType:           "Convertible",
			Condition:          "Brand New",
			Mileage:            50,
			Transmission:       "Automatic",
			FuelType:           "Petrol",
			EngineSize:         "3.0L Turbo Inline-6",
			VIN:                "WBAHF3C08PW019284",
			Price:              64000000,
			MarketPriceMin:     62000000,
			MarketPriceMax:     68000000,
			PriceRating:        "fair",
			PriceVerdict:       "Showroom fresh 382 hp twin-scroll convertible with power soft top.",
			TrustTier:          5,
			TrustTierLabel:     "Premium Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679189/carplug/cars/car18.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679179/carplug/cars/car4.jpg"]`,
			PublicLocation:     "Victoria Island, Lagos",
			ExactLocation:      "Ahmadu Bello Way, VI",
			SellerID:           "dealer-apex-motors",
			SellerType:         "dealer",
			SellerName:         "Apex Exotic Motors",
			SellerPhone:        "+234 802 333 7799",
			SellerRating:       5.0,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        99,
			Featured:           true,
		},

		// --- Electric Category ---
		{
			ID:                 "v-porsche-taycan-2023",
			Title:              "2023 Porsche Taycan 4S Electric AWD",
			Year:               2023,
			Make:               "Porsche",
			Model:              "Taycan",
			Trim:               "4S Electric",
			BodyType:           "Electric",
			Condition:          "Brand New",
			Mileage:            30,
			Transmission:       "Automatic",
			FuelType:           "Electric",
			EngineSize:         "Dual Permanent Magnet Motors",
			VIN:                "WP0AB2Y11PSA91823",
			Price:              118000000,
			MarketPriceMin:     112000000,
			MarketPriceMax:     125000000,
			PriceRating:        "fair",
			PriceVerdict:       "Zero emissions luxury sports car with Performance Battery Plus and 800V fast charging.",
			TrustTier:          5,
			TrustTierLabel:     "Premium Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679187/carplug/cars/car16.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679188/carplug/cars/car17.jpg"]`,
			PublicLocation:     "Victoria Island, Lagos",
			ExactLocation:      "Ahmadu Bello Way, VI",
			SellerID:           "dealer-apex-motors",
			SellerType:         "dealer",
			SellerName:         "Apex Exotic Motors",
			SellerPhone:        "+234 802 333 7799",
			SellerRating:       5.0,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        100,
			Featured:           true,
		},

		// --- Hybrid / Alternate ---
		{
			ID:                 "v-lexus-rx450h-2021",
			Title:              "2021 Lexus RX 450h F-Sport Hybrid AWD",
			Year:               2021,
			Make:               "Lexus",
			Model:              "RX",
			Trim:               "450h Hybrid",
			BodyType:           "SUV",
			Condition:          "Foreign Used (Tokunbo)",
			Mileage:            26000,
			Transmission:       "Automatic",
			FuelType:           "Hybrid",
			EngineSize:         "3.5L V6 Hybrid Synergy Drive",
			VIN:                "2T2BGMCA7MC091824",
			Price:              37000000,
			MarketPriceMin:     35000000,
			MarketPriceMax:     39000000,
			PriceRating:        "deal",
			PriceVerdict:       "Top fuel economy Tokunbo luxury SUV with certified hybrid battery health report.",
			TrustTier:          5,
			TrustTierLabel:     "Premium Verified",
			Images:             `["https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679186/carplug/cars/car15.jpg", "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679188/carplug/cars/car17.jpg"]`,
			PublicLocation:     "Lekki Phase 1, Lagos",
			ExactLocation:      "Plot 14 Admiralty Way, Lekki",
			SellerID:           "dealer-reed-motors",
			SellerType:         "dealer",
			SellerName:         "Reed Motors Lagos",
			SellerPhone:        "+234 803 500 4401",
			SellerRating:       4.9,
			CustomsStatus:      "Fully Cleared",
			CustomsDoc:         true,
			RegistrationDoc:    true,
			Roadworthiness:     true,
			HealthScore:        93,
			Featured:           true,
		},
	}

	log.Println("[Seed] Upserting Vehicles catalog...")
	for _, v := range vehicles {
		db.Save(&v)
	}

	// 5. Seed Campaigns
	var campCount int64
	db.Model(&Campaign{}).Count(&campCount)
	if campCount == 0 {
		log.Println("[Seed] Seeding initial Campaigns...")
		campaigns := []Campaign{
			{
				ID:                   "camp-01",
				Advertiser:           "Leadway Auto Insurance",
				Placement:            "Vehicle Health Report Sponsor",
				CreativeImage:        "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679188/carplug/cars/car17.jpg",
				Budget:               360000,
				Dates:                "Sep 01 - Sep 15, 2026",
				ImpressionsDelivered: 42300,
				ImpressionGoal:       60000,
				Clicks:               1820,
				Status:               "Active",
				TargetCity:           "Nationwide",
			},
			{
				ID:                   "camp-02",
				Advertiser:           "Stanbic IBTC Auto Loans",
				Placement:            "Homepage Brand Spotlight",
				CreativeImage:        "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679186/carplug/cars/car15.jpg",
				Budget:               500000,
				Dates:                "Sep 03 - Sep 17, 2026",
				ImpressionsDelivered: 112000,
				ImpressionGoal:       200000,
				Clicks:               4680,
				Status:               "Active",
				TargetCity:           "Lagos & Abuja",
			},
		}
		for _, c := range campaigns {
			db.FirstOrCreate(&c, Campaign{ID: c.ID})
		}
	}

	// 6. Seed Swaps
	var swapCount int64
	db.Model(&SwapRequest{}).Count(&swapCount)
	if swapCount == 0 {
		log.Println("[Seed] Seeding initial SwapRequests...")
		swaps := []SwapRequest{
			{
				ID:               "swap-101",
				CustomerName:     "Chukwuma Reed",
				CustomerPhone:    "+234 803 291 0021",
				CurrentCar:       "2017 Toyota Camry LE (74k mi)",
				CurrentCarImage:  "https://res.cloudinary.com/cgiq8vwf/image/upload/v1789679184/carplug/cars/car13.jpg",
				AppraisedEquity:  15000000,
				TargetCar:        "2021 Lexus RX 350 F-Sport",
				TargetCarPrice:   38500000,
				PlatformDiscount: 1925000,
				NetTopUp:         21575000,
				Status:           "In Audit",
				ScheduledDate:    "Sep 08, 2026",
				AssignedTech:     "Engr. Tunde Adeleke",
			},
		}
		for _, s := range swaps {
			db.FirstOrCreate(&s, SwapRequest{ID: s.ID})
		}
	}

	// 7. Seed Transactions (Financial Ledger)
	var txnCount int64
	db.Model(&Transaction{}).Count(&txnCount)
	if txnCount == 0 {
		log.Println("[Seed] Seeding initial Transactions...")
		txns := []Transaction{
			{
				ID:        "txn-8091",
				Reference: "CP-TXN-1789001-PAYSTACK",
				UserID:    "dealer-reed-motors",
				UserName:  "Reed Motors Lagos",
				UserEmail: "dealer.reed@mycars.ng",
				UserRole:  "dealer",
				Type:      "dealer_subscription",
				Title:     "Dealer Subscription (Pro Shop)",
				Amount:    65000,
				Currency:  "NGN",
				Gateway:   "paystack",
				Status:    "settled",
				Notes:     "30-day Pro Showroom Plan activated via Paystack card payment",
			},
			{
				ID:        "txn-8090",
				Reference: "CP-TXN-1789002-ESCROW",
				UserID:    "usr-buyer-chidi",
				UserName:  "Dr. Chidi Nwosu",
				UserEmail: "buyer.chidi@mycars.ng",
				UserRole:  "buyer",
				Type:      "inspection_escrow",
				Title:     "150-Point Inspection Escrow Deposit",
				Amount:    75000,
				Currency:  "NGN",
				Gateway:   "paystack",
				Status:    "held_in_escrow",
				Notes:     "Held in Carplug Secure Escrow pending technician report verification",
			},
			{
				ID:        "txn-8089",
				Reference: "CP-TXN-1789003-PAYOUT",
				UserID:    "tech-musa",
				UserName:  "Musa Danladi, ASE-Cert",
				UserEmail: "tech.musa@mycars.ng",
				UserRole:  "technician",
				Type:      "tech_payout",
				Title:     "Technician Inspection Payout Settlement",
				Amount:    35000,
				Currency:  "NGN",
				Gateway:   "bank_transfer",
				Status:    "settled",
				Notes:     "Disbursed to Access Bank • 0123984712 • Musa Danladi",
			},
			{
				ID:        "txn-8088",
				Reference: "CP-TXN-1789004-CROWN",
				UserID:    "dealer-crown-autos",
				UserName:  "Crown Continental Autos",
				UserEmail: "dealer.crown@mycars.ng",
				UserRole:  "dealer",
				Type:      "dealer_subscription",
				Title:     "Dealer Subscription (Pro Shop)",
				Amount:    65000,
				Currency:  "NGN",
				Gateway:   "paystack",
				Status:    "settled",
				Notes:     "30-day Pro Showroom Plan activated",
			},
			{
				ID:        "txn-8087",
				Reference: "CP-TXN-1789005-AMINA",
				UserID:    "usr-buyer-chidi",
				UserName:  "Dr. Chidi Nwosu",
				UserEmail: "buyer.chidi@mycars.ng",
				UserRole:  "buyer",
				Type:      "inspection_escrow",
				Title:     "Standard Pre-Purchase Inspection Fee",
				Amount:    45000,
				Currency:  "NGN",
				Gateway:   "paystack",
				Status:    "settled",
				Notes:     "Inspection completed and funds disbursed to technician",
			},
		}
		for _, t := range txns {
			db.FirstOrCreate(&t, Transaction{ID: t.ID})
		}
	}
}
